import { KeyboardRow } from "../ui/Keyboard/Key/Key.types";

const row1: KeyboardRow = {
  keys: [
    {
      top: "~",
      topDescription: "toggle case",
      topMode: "insert",
      bottom: "`",
      bottomDescription: "jump to mark",
      bottomMode: "motion",
    },
    {
      top: "!",
      topDescription: "external filter",
      topMode: "visual",
      bottom: "1",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "@",
      topDescription: "play macro",
      topMode: "motion",
      bottom: "2",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "#",
      topDescription: "search backw.",
      topMode: "motion",
      bottom: "3",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "$",
      topDescription: "end of line",
      topMode: "motion",
      bottom: "4",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "%",
      topDescription: "goto match",
      topMode: "motion",
      bottom: "5",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "^",
      topDescription: `"soft" begin of line`,
      topMode: "insert",
      bottom: "6",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "&",
      topDescription: "repeat :s",
      topMode: "motion",
      bottom: "7",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "*",
      topDescription: "search forward",
      topMode: "motion",
      bottom: "8",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: "(",
      topDescription: "begin seq.",
      topMode: "motion",
      bottom: "9",
      bottomDescription: undefined,
      bottomMode: "none",
    },
    {
      top: ")",
      topDescription: "end seq.",
      topMode: "motion",
      bottom: "0",
      bottomDescription: `"hard" bol`,
      bottomMode: "motion",
    },
    {
      top: "_",
      topDescription: `"soft" bol`,
      topMode: "motion",
      bottom: "-",
      bottomDescription: "prev. line",
      bottomMode: "motion",
    },
    {
      top: "+",
      topDescription: "next line",
      topMode: "motion",
      bottom: "=",
      bottomDescription: "auto format",
      bottomMode: "visual",
    },
  ],
};

export default row1;
