import { KeyboardRow } from "../ui/Keyboard/Key/Key.types";

const row3: KeyboardRow = {
  initialKey: {
    button: "caps lock",
    width: 1.75,
  },
  keys: [
    {
      top: "A",
      topDescription: "append at col",
      topMode: "insert",
      bottom: "a",
      bottomDescription: "append",
      bottomMode: "insert",
    },
    {
      top: "S",
      topDescription: "substitute line",
      topMode: "insert",
      bottom: "s",
      bottomDescription: "substitute character",
      bottomMode: "insert",
    },
    {
      top: "D",
      topDescription: "delete to col",
      topMode: "insert",
      bottom: "d",
      bottomDescription: "delete",
      bottomMode: "visual",
    },
    {
      top: "F",
      topDescription: `"back" find char.`,
      topMode: "motion",
      bottom: "f",
      bottomDescription: "find char.",
      bottomMode: "motion",
    },
    {
      top: "G",
      topDescription: "goto end of line",
      topMode: "motion",
      bottom: "g",
      bottomDescription: "extra cmds",
      bottomMode: "none",
    },
    {
      top: "H",
      topDescription: "screen top",
      topMode: "motion",
      bottom: "h",
      bottomDescription: "←",
      bottomMode: "motion",
    },
    {
      top: "J",
      topDescription: "join lines",
      topMode: "insert",
      bottom: "j",
      bottomDescription: "↓",
      bottomMode: "motion",
    },
    {
      top: "K",
      topDescription: "look up keyword",
      topMode: "insert",
      bottom: "k",
      bottomDescription: "↑",
      bottomMode: "motion",
    },
    {
      top: "L",
      topDescription: "screen bottom",
      topMode: "motion",
      bottom: "l",
      bottomDescription: "→",
      bottomMode: "motion",
    },
    {
      top: ":",
      topDescription: "cmd_line",
      topMode: "insert",
      bottom: ";",
      bottomDescription: "repeat (t/T/f/F)",
      bottomMode: "motion",
    },
    {
      top: `"`,
      topDescription: "register spec",
      topMode: "none",
      bottom: `'`,
      bottomDescription: "goto mark",
      bottomMode: "motion",
    },
  ],
};

export default row3;
