import { KeyboardRow } from "../ui/Keyboard/Key/Key.types";

const row3: KeyboardRow = {
  initialKey: {
    button: "caps lock",
    width: 1.75,
  },
  keys: [
    {
      top: "A",
      topDescription: "ex mode",
      topMode: "insert",
      bottom: "a",
      bottomDescription: "record macros",
      bottomMode: "insert",
    },
    {
      top: "S",
      topDescription: "next WORD",
      topMode: "motion",
      bottom: "s",
      bottomDescription: "next word",
      bottomMode: "motion",
    },
    {
      top: "D",
      topDescription: "end WORD",
      topMode: "motion",
      bottom: "d",
      bottomDescription: "end word",
      bottomMode: "motion",
    },
    {
      top: "F",
      topDescription: "replace mode",
      topMode: "insert",
      bottom: "f",
      bottomDescription: "replace character",
      bottomMode: "insert",
    },
    {
      top: "G",
      topDescription: "back 'till",
      topMode: "motion",
      bottom: "g",
      bottomDescription: "'til",
      bottomMode: "motion",
    },
    {
      top: "H",
      topDescription: "yank line",
      topMode: "insert",
      bottom: "h",
      bottomDescription: "yank",
      bottomMode: "visual",
    },
    {
      top: "J",
      topDescription: "undo line",
      topMode: "insert",
      bottom: "j",
      bottomDescription: "undo",
      bottomMode: "insert",
    },
    {
      top: "K",
      topDescription: "insert at beginning",
      topMode: "insert",
      bottom: "k",
      bottomDescription: "insert mode",
      bottomMode: "insert",
    },
    {
      top: "L",
      topDescription: "open above",
      topMode: "insert",
      bottom: "l",
      bottomDescription: "open below",
      bottomMode: "insert",
    },
    {
      top: ":",
      topDescription: "paste before",
      topMode: "insert",
      bottom: ";",
      bottomDescription: "paste after",
      bottomMode: "insert",
    },
    {
      top: `"`,
      topDescription: "paste before",
      topMode: "insert",
      bottom: `'`,
      bottomDescription: "paste after",
      bottomMode: "insert",
    },
  ],
};

export default row3;
